# Generated by Django 4.1.7 on 2023-03-21 14:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Store', '0003_products_rom'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Customer', '0002_delete_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=200)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commented_post', to='Store.products')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commented_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='m_cart', to='Store.products')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='m_cart', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
