# Generated by Django 4.1.7 on 2023-03-23 02:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0003_products_rom'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Customer', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='mobile',
        ),
        migrations.AlterField(
            model_name='cart',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='u_cart', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='review',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commented_product', to='Store.products'),
        ),
        migrations.AddField(
            model_name='cart',
            name='mobile',
            field=models.ManyToManyField(related_name='m_cart', to='Store.products'),
        ),
    ]
