# Generated by Django 4.1.7 on 2023-03-23 02:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0003_products_rom'),
        ('Customer', '0004_remove_cart_mobile_alter_cart_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='mobile',
        ),
        migrations.AddField(
            model_name='cart',
            name='mobile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='m_cart', to='Store.products'),
        ),
    ]
