# Generated by Django 4.1.7 on 2023-03-24 08:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0003_products_rom'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Customer', '0005_remove_cart_mobile_cart_mobile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('mobile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='m_purchase', to='Store.products')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='u_purchase', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
