# Generated by Django 4.1.7 on 2023-03-24 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0006_purchase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='quantity',
        ),
    ]
