# Generated by Django 4.1.7 on 2023-03-25 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0007_remove_purchase_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='status',
            field=models.CharField(choices=[('carted', 'carted'), ('purchased', 'purchased')], default='carted', max_length=100),
        ),
    ]
