# Generated by Django 4.1.7 on 2023-03-25 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0008_cart_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseDetailes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('post', models.CharField(max_length=100)),
                ('pin', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('purchase', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='p_detailes', to='Customer.purchase')),
            ],
        ),
    ]
