# Generated by Django 4.1.7 on 2023-03-25 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0009_purchasedetailes'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='city',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='pin',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='post',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='quantity',
            field=models.IntegerField(null=True),
        ),
        migrations.DeleteModel(
            name='PurchaseDetailes',
        ),
    ]
