# Generated by Django 4.1.7 on 2023-03-25 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0010_purchase_city_purchase_pin_purchase_post_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='status',
            field=models.CharField(choices=[('carted', 'carted'), ('purchased', 'purchased')], default='purchased', max_length=100),
        ),
    ]
