# Generated by Django 4.1.7 on 2023-03-26 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='custuser',
            name='image',
        ),
    ]
