# Generated by Django 4.1.7 on 2023-03-21 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='processer',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='ram',
            field=models.IntegerField(null=True),
        ),
    ]
