# Generated by Django 4.1.7 on 2023-03-21 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0002_products_processer_products_ram'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='rom',
            field=models.IntegerField(null=True),
        ),
    ]
